//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMethod {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Sys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Sys defaultInstance = ((Sys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Sys())));
        
        public static Sys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FileLogFactory")]
        public string FactoryName {
            get {
                return ((string)(this["FactoryName"]));
            }
            set {
                this["FactoryName"] = value;
            }
        }
    }
}
